SmarterApp/DL_DigitalLibrary2.0

webapp/src/app/common/controls/button/button.component.html, webapp/src/app/common/controls/button/button.component.ts, webapp/src/app/common/controls/popover/popover.component.html, webapp/src/app/common/controls/popover/popover.component.scss, webapp/src/app/common/controls/popover/popover.component.ts, webapp/src/app/resource/instructional/content/resource-content.component.html, webapp/src/app/resource/instructional/content/resource-content.component.scss, webapp/src/app/resource/instructional/differentiation/differentiation.component.html, webapp/src/app/resource/instructional/differentiation/differentiation.component.scss, webapp/src/app/resource/instructional/formative/formative.component.html, webapp/src/app/resource/instructional/formative/formative.component.scss, webapp/src/app/resource/instructional/instructional-resource.component.html, webapp/src/app/resource/instructional/instructional-resource.component.scss, webapp/src/app/resource/instructional/overview/overview.component.html, webapp/src/app/resource/instructional/overview/overview.component.scss, webapp/src/app/resource/metadata/metadata.component.html, webapp/src/app/resource/metadata/metadata.component.scss, webapp/src/app/resource/outline/outline.component.html, webapp/src/app/resource/outline/outline.component.scss, webapp/src/app/resource/outline/outline.component.ts
This PR fixes styling issues, improves consistency of css code, and adds highlighting functionality when clicked in the outline.
=> As ui infrastructure

operations/util/update-version.sh, webapp/package-lock.json, webapp/package.json, webapp/src/app/app-routing.module.ts, webapp/src/app/app.module.ts, webapp/src/app/bookmarks/bookmark-card/bookmark-card.component.html, webapp/src/app/data/notes/model/note.model.ts, webapp/src/app/notes/note/note.component.html, webapp/src/app/notes/note/note.component.scss, webapp/src/app/notes/note/note.component.ts, webapp/src/app/notes/notes.component.html, webapp/src/app/notes/notes.component.scss, webapp/src/app/notes/notes.component.ts, webapp/src/app/notes/notes.module.ts, webapp/src/app/notes/notes.resolve.ts, webapp/src/app/resource/components/actions/actions.component.html, webapp/src/app/resource/components/actions/actions.component.scss, webapp/src/app/resource/components/actions/actions.component.ts, webapp/src/app/resource/instructional/content/instructional-content.component.html, webapp/src/app/resource/instructional/instructional-resource.component.html, webapp/src/app/resource/professional/content/professional-content.component.html, webapp/src/app/resource/professional/professional-resource.component.html, webapp/src/app/resource/resource-content.component.ts, webapp/src/app/resource/resource-type-strategy.component.ts, webapp/src/app/resource/resource.component.ts, webapp/src/app/resource/resource.module.ts, webapp/src/ui-kit/_buttons.scss
=> Notes UI Functionality

webapp/src/app/app.module.ts, webapp/src/app/bookmarks/bookmark-card/bookmark-card.component.html, webapp/src/app/bookmarks/bookmark-list/bookmark-list.component.ts, webapp/src/app/common/controls/popover/popover.service.ts, webapp/src/app/common/controls/tooltip/tooltip.component.html, webapp/src/app/common/controls/tooltip/tooltip.component.scss, webapp/src/app/home/home.component.ts, webapp/src/app/layout/app-container/app-container.component.html, webapp/src/app/layout/navigation/navigation.component.html, webapp/src/app/layout/navigation/navigation.component.scss, webapp/src/app/resource/components/resource-properties/resource-properties.component.html, webapp/src/app/resource/components/strategy-reference-list/strategy-reference-list.component.html, webapp/src/app/resource/instructional/instructional-resource.component.html, webapp/src/app/resource/instructional/instructional-resource.component.ts, webapp/src/app/resource/professional/professional-resource.component.html, webapp/src/app/resource/professional/professional-resource.component.ts, webapp/src/app/resource/resource.component.ts, webapp/src/app/resource/strategy/strategy-resource.component.html, webapp/src/app/resource/strategy/strategy-resource.component.ts, webapp/src/index.html
Addresses:
* [DL-206](https://smarterbalanced.atlassian.net/browse/DL-206): tooltip buttons and popup contents are not accessible.
* [DL-210](https://smarterbalanced.atlassian.net/browse/DL-210): Missing "skip links". This does not add skip links but does properly define page landmarks which serve a similar purpose. We may still need ton consider adding skip links.
* [DL-211](https://smarterbalanced.atlassian.net/browse/DL-211): Each page should have a unique title.
* [DL-207](https://smarterbalanced.atlassian.net/browse/DL-207): User is not informed when links will open in new tabs/windows.
=> Accessibility fixes

webapp/src/app/resource/components/resource-properties/educational-details.component.html
Fixes DL-202: https://smarterbalanced.atlassian.net/browse/DL-202
=> DL-202: Remove commas trailing target descriptions.

webapp/src/app/bookmarks/bookmark-actions/bookmark-actions.component.html, webapp/src/app/common/controls/filter-chipset/filter-chipset.component.html, webapp/src/app/layout/footer/footer.component.html, webapp/src/app/layout/footer/footer.component.scss, webapp/src/app/layout/navigation/navigation.component.html, webapp/src/app/notes/notes.component.html, webapp/src/app/resource/components/attachments/card/attachment-card.component.html, webapp/src/app/resource/components/strategy-reference-list/strategy-reference-list.component.html, webapp/src/app/resource/playlist/background/playlist-background.component.html, webapp/src/app/resource/playlist/interim/playlist-interim.component.html, webapp/src/app/resource/playlist/intervention/playlist-intervention.component.html, webapp/src/app/resource/playlist/resources/playlist-resources.component.html, webapp/src/app/resource/playlist/topics/playlist-topic.component.html, webapp/src/app/resource/strategy/properties/strategy-properties.component.html, webapp/src/app/resource/strategy/strategy-in-action/strategy-in-action-accessibility.component.html, webapp/src/app/search/search.component.html
Additionally I've  added `aria-hidden` attributes as appropriate on images I found along the way.
=> DL-207 Clearly label all links that open in new windows.

webapp/src/app/app-routing.module.ts, webapp/src/app/app.component.ts, webapp/src/app/resource/components/outline/outline.component.ts, webapp/src/app/resource/playlist/interim/playlist-interim.component.html, webapp/src/app/resource/playlist/interim/playlist-interim.component.scss, webapp/src/app/resource/strategy/properties/strategy-properties.component.scss, webapp/src/app/router.service.ts
=> DL-298 DL-271 Scroll to top on new page, support deep-linking to page anchors.

webapp/src/app/resource/components/preview-login-prompt/preview-login-prompt.component.html, webapp/src/app/resource/components/preview-login-prompt/preview-login-prompt.component.scss, webapp/src/app/resource/components/preview-login-prompt/preview-login-prompt.component.ts, webapp/src/app/resource/components/protected-content/protected-content.component.html, webapp/src/app/resource/components/protected-content/protected-content.component.scss, webapp/src/app/resource/components/protected-content/protected-content.component.spec.ts, webapp/src/app/resource/components/protected-content/protected-content.component.ts, webapp/src/app/resource/instructional/content/instructional-content.component.html, webapp/src/app/resource/instructional/instructional-resource.component.html, webapp/src/app/resource/playlist/content/playlist-content.component.html, webapp/src/app/resource/playlist/playlist-resource.component.html, webapp/src/app/resource/professional/content/professional-content.component.html, webapp/src/app/resource/professional/professional-resource.component.html, webapp/src/app/resource/resource.component.scss, webapp/src/app/resource/resource.module.ts, webapp/src/app/resource/strategy/content/strategy-content.component.html, webapp/src/app/resource/strategy/strategy-resource.component.html, webapp/src/ui-kit/_mixins.scss
=> fixes some interaction issues with teaser overlay

webapp/src/app/data/user/user.service.ts, webapp/src/app/resource/components/actions/actions.component.html, webapp/src/app/resource/components/actions/actions.component.ts, webapp/src/app/resource/components/protected-content/protected-content.component.scss, webapp/src/app/resource/instructional/instructional-resource.component.html, webapp/src/app/resource/playlist/content/playlist-content.component.html, webapp/src/app/resource/playlist/playlist-resource.component.html, webapp/src/app/resource/professional/professional-resource.component.html, webapp/src/app/resource/resource-content.component.ts, webapp/src/app/resource/resource-type-strategy.component.ts, webapp/src/app/resource/resource.component.ts, webapp/src/app/resource/strategy/strategy-resource.component.html
=> fixes playlist blurring

webapp/src/ui-kit/_icons.scss
=> fixes tooltip color

webapp/src/app/common/error-type.enum.ts, webapp/src/app/layout/error/error.component.html, webapp/src/app/layout/error/error.component.scss, webapp/src/app/layout/error/error.component.ts, webapp/src/app/layout/login-callback/login-callback.component.ts, webapp/src/app/resource/components/preview-login-prompt/preview-login-prompt.component.ts, webapp/src/assets/config/config.prod.json
This is not entirely finished, but pushing so Nohemi can test as much as possible.
=>  DL-64 Graceful error pages. 

webapp/src/app/resource/resource-type-strategy.component.ts
was able to test - this fixed the issue
=> adds merge param option

webapp/src/app/app-routing.module.ts, webapp/src/app/pipes/replace-null-image.pipe.ts, webapp/src/app/pipes/safe-url.pipe.ts, webapp/src/app/resource/components/resource-properties/resource-properties.component.html, webapp/src/app/resource/components/resource-properties/resource-properties.component.scss, webapp/src/app/resource/components/resource-properties/resource-properties.component.ts, webapp/src/app/resource/components/resource-summary-card/resource-summary-card.component.html, webapp/src/app/resource/components/resource-summary-card/resource-summary-card.component.scss, webapp/src/app/resource/components/resource-summary-card/resource-summary-card.component.ts, webapp/src/app/resource/components/resource-thumbnail/resource-thumbnail.component.html, webapp/src/app/resource/components/resource-thumbnail/resource-thumbnail.component.scss, webapp/src/app/resource/components/resource-thumbnail/resource-thumbnail.component.spec.ts, webapp/src/app/resource/components/resource-thumbnail/resource-thumbnail.component.ts, webapp/src/app/resource/resource.module.ts
** github not able to upload images at the moment so i'm dropping them on your doorstep in slack **
=> fixes bookmark thumb and summary display

webapp/src/app/resource/components/resource-summary-card/resource-summary-card.component.html, webapp/src/app/resource/components/resource-summary-card/resource-summary-card.component.ts
=> adds metadata for connections playlist bookmarks

webapp/src/app/resource/components/simple-section/simple-section.component.html
took me way too long to figure this out
=> fixes link highlights

webapp/src/app/resource/components/outline/outline.component.ts, webapp/src/app/resource/playlist/topics/playlist-topics.component.scss, webapp/src/app/resource/resource.component.scss, webapp/src/ui-kit/_mixins.scss
not super pleased with this but it worked.
=> adds highlighting to table rows

webapp/src/app/resource/components/header/header.component.html, webapp/src/app/resource/components/header/header.component.scss, webapp/src/app/resource/components/outline/outline.component.ts, webapp/src/app/resource/resource.component.ts, webapp/src/styles.scss
TODOs:
1. tabbing inside of attachment modal
2. tabbing position after closing modal
=> Dl 389 wcag concerns

webapp/src/app/common/controls/read-more/read-more.component.html, webapp/src/app/common/tft-error-type.enum.ts, webapp/src/index.html, webapp/src/ui-kit/_typography.scss
* TFT-32 MathML support.
* TFT-86 Type in error message.
* TFT-99 Change .emphasis-medium opacity
=> MathML Support, small bugfixes.

webapp/src/app/layout/login/login.component.html, webapp/src/assets/config/config.dev.json, webapp/src/assets/config/config.qa.json, webapp/src/assets/config/config.uat.json, webapp/src/assets/config/tenant.config.json
merge pull request to modify release branch:
T4T-347: CT links
T4T-354: VI links
T4T-355: VT links
T4T-443: prelogin text corrections
T4T-444: MI and OR links
T4T-448: Update IAIP non-prod link for DEV/QA/UAT environments
=> Typo, tenant specific and link update fix to release branch

webapp/src/assets/config/tenant.config.json
Updated tenant assessment portal links (Cambium) for USVI, CT, idaho, WA, DE, SD (T4T-453)
=> Update Cambium portal link fix to release branch (T4T-453)

webapp/src/app/data/bookmarks/bookmarks.service.ts, webapp/src/app/notes/notes.component.ts
Updating bookmark and note service to resolve the duplication of bookmarks in the UI (T4T-439)
=> Apply Bookmark Duplication fix to release 1.3.x

webapp/src/app/notes/notes.component.ts
Updating notes component typescript to fix delete error caused by ngoninit subscription firing multiple time. (T4T-450)
=> Apply Note Deletion error fix to 1.3 release

webapp/src/app/common/config/config.model.ts, webapp/src/app/data/user/user.service.ts, webapp/src/app/layout/navigation/navigation.component.html, webapp/src/app/layout/navigation/navigation.component.ts, webapp/src/assets/config/config.prod.json
Enable access to IAIP via Tools for Teachers navigation bar based on authentication.
=> Adding IAIP Portal Link

webapp/src/app/layout/footer/footer.component.html, webapp/src/app/layout/footer/footer.component.scss
=> Revert "test deployment issue"

webapp/src/styles.scss
Reverts SmarterApp/DL_DigitalLibrary2.0#328
=> Revert "Updating the copyright year to reflect 2021"

webapp/src/app/data/resource/embed-strategy-links.service.ts
updated the class EmbedStrategyLinksService to encode for parenthesis when they are in the strategy's title.
=> Feature/T4T-639 handle parenthesis in strategy's title

webapp/src/app/home/home.component.html
=> T4T-646 Replace the Understanding Assessment Video on the homepage

webapp/src/app/resource/resource.component.scss
All the changes for fixing the footer and then the header and content
Note: new PR
=> T4T-642 Changes for footer

webapp/src/app/app.component.ts, webapp/src/app/app.module.ts, webapp/src/app/common/config/config.model.ts, webapp/src/app/google-analytics.service.spec.ts, webapp/src/app/google-analytics.service.ts, webapp/src/assets/config/config.dev.json, webapp/src/assets/config/config.json, webapp/src/assets/config/config.prod.json, webapp/src/assets/config/config.qa.json, webapp/src/assets/config/config.stage.json, webapp/src/assets/config/config.uat.json, webapp/src/index.html
This will turn off GA3 in non-prod environments and do GA4 in all environments but, with a different tracking number in prod
=> T4T-652 - Changes for GA4

webapp/src/app/resource/resource.component.scss
A fix for Firefox and the change on the footer issue (T4T-642)
=> T4t-370 Adding the IAIP buttons

webapp/src/app/resource/resource.component.scss
Reverts SmarterApp/DL_DigitalLibrary2.0#347
=> Revert "T4t-370 Adding the IAIP buttons"

webapp/src/app/common/controls/able-player-float-ts/able-player-float-ts.component.html, webapp/src/app/resource/components/able-player/able-player.component.html
made the default for captions to be overlaid.
=> T4T-734 - default captions to overlay

webapp/src/app/common/controls/text-field/text-field.component.scss, webapp/src/app/landing/landing-actions/landing-actions.component.html, webapp/src/app/landing/landing-common.component.scss, webapp/src/app/landing/landing-dive-deeper/landing-dive-deeper.component.html, webapp/src/app/landing/landing-sample-items/landing-sample-items.component.html, webapp/src/app/landing/landing.component.html, webapp/src/app/landing/landing.component.scss, webapp/src/app/landing/landing.component.ts, webapp/src/app/layout/navigation/navigation.component.html, webapp/src/app/layout/navigation/navigation.component.scss, webapp/src/app/search/search.component.scss
Fixed items: QAResult-1, QAResult-2, QAResult-3, QAResult-4, QAResult-5, QAResult-7, QAResult-8, QAResult-9, QAResult-10, QAResult-11, QAResult-13 and QAResult-16
=> T4T-768 QA first cut at changes

webapp/src/app/common/tft-error-type.enum.ts
https://smarterbalanced.atlassian.net/browse/T4T-807
=> T4T-807 Update error-handling message

webapp/src/app/common/controls/able-player-float-ts/able-player-float-ts.component.html
HOTFIX TEST FOR STAGING
Change Able Players default skin to 2020 version to fix icon issues
https://smarterbalanced.atlassian.net/secure/RapidBoard.jspa?rapidView=43&modal=detail&selectedIssue=T4T-823
=> T4T-823 - Change Able Players default skin to 2020 version

webapp/src/app/common/controls/able-player-float-ts/able-player-float-ts.component.html
Reverts SmarterApp/DL_DigitalLibrary2.0#387
=> Revert "T4T-823 - Change Able Players default skin to 2020 version"

webapp/src/app/app-routing.module.ts
Add redirects for different resources based on PDF print links
=> T4T-830 - Landing page URL in Printable
